### ISSUE TITLE
src/README has possible typo

### ISSUE THREAD

**Issue by ksnortum** [MutopiaProject/MutopiaWeb#14]
In describing how the software is built, the README states:

``` bash
$ cd src/Mutopia_Archive
$ perl ./Build.PL --install_base=$HOME/MutopiaWeb
$ ./Build
$ ./Build test
$ ./Build install
```

But `--install_base` is not a valid option.  It seems to "fail" quietly, defaulting to the home folder.  But `--install-base` (no underscore) _is_ a valid option, and installs the programs in `lib`, probably where they should be.  But the `.pm` programs sometimes assume they are in MUTOPIA_WEB.  This may have to change.

**Comment by ksnortum** [comment]
My opinion is that a `lib` program should never make assumptions about where it's installed, because if you move it, it breaks.  If PERL5LIB ever has to change, the software will not work.

On the other hand, I don't think making the `.pm` programs "location agnostic" will be trivial.

**Comment by glenl** [comment]
Regarding --install_base: please check that your version of Module::Build is up-to-date. This is a valid option in 0.4214 (--install-base is not a valid option.) I'll use a different method of controlling library builds if this can't be relied on. I agree that the method of finding required locations needs to be improved.

**Comment by ksnortum** [comment]
You're right,  `--install_base` is the correct option.  I don't know how I got it backwards.  I'll close this issue without updating.
