### ISSUE TITLE
Javadoc & tests for java utilities

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaWeb#17]
Need javadoc for MutopiaPIece, MutopiaRDF.
Need tests for everything.

**Comment by ksnortum** [comment]
This is right up my ally.

**Comment by glenl** [comment]
It is not that I can't make up my mind regarding assignment, but I was hoping we could both be assigned to this. I've written some basic tests for the new `LicenseMap` I wrote recently and I want to add some for `MutopiaMaps`.

@ksnortum - Do you want to take `MutopiaRDF` and `MutopiaPiece` ? They need unit tests and javadoc commentary.

**Comment by ksnortum** [comment]
I will do that.

Knute Snortum
(via Gmail)
