### ISSUE TITLE
Jumbotron and logo

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaWeb#19]
The "logo" sits inside a bootstrap "Jumbotron" as a grid that is divided up to replicate the original site. The left third of the grid is the logo, the middle the "mission statement" and the right contains links to mirrors for the site.
- Does it have to be this big?
- The logo was meant,
  - as a placeholder for the eventual, "real" logo
  - to see how well vector graphics (svg) work in the browser

I like the look of this but it was done without oversight or feedback. It is time for that.

About the logo: It was created in inkscape and uses the inkscape svg file directly. The font is an open source font called "Utopia"; the name fits our purpose and looks nice. The characters were converted to a path and manipulated slightly. The color was matched from the previous logo.

**Comment by ksnortum** [comment]
See also #32
