### ISSUE TITLE
Clicking "hamburger" button does not show a menu

### ISSUE THREAD

**Issue by PaulMorris** [MutopiaProject/MutopiaWeb#24]
When I view the demo site[0] on a small window/screen, using my phone or the Firefox responsive design view[1], the "hamburger" button (3 horizontal lines) appears on the right side of the menu bar, but clicking it does not show a menu.

[0] http://www.mutopiaproject.org/new/index.html
[1] https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_View

**Comment by PaulMorris** [comment]
It seems that this isn't working because the bootstrap js file is not being loaded since it can't be found at:
http://www.mutopiaproject.org/new/dist/js/bootstrap.min.js

...and that's where the demo site is trying to load it from.  It needs to be this instead:
http://www.mutopiaproject.org/new/bootstrap-3.3.5-dist/js/bootstrap.min.js

...and it looks like the source code is already correct on this, just not the demo site.

**Comment by glenl** [comment]
This is the very first population of the "new" folder on the site and it confirmed that things "mostly" work in that configuration. I'll push for a rebuild of the new site this week since there have been a few changes. Thanks for noticing this.

**Comment by PaulMorris** [comment]
Works fine in Prototype 2
