### ISSUE TITLE
IE clips lower part of logo in banner

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaWeb#3]
The "banner" is a bootstrap "jumbotron", defined in their CSS.
There are some tweaks in mutopia.css so it wouldn't be so high; the problem is probably there.

**Comment by glenl** [comment]
One thing we may want to try before too much head-banging is to load the latest bootstrap v3.3.6 (we are currently at 3.3.5). I don't think this will change that often a strategy for moving between revisions would be a good thing. It may be a while before we go to bootstrap 4.0.

**Comment by ksnortum** [comment]
I tried updating to bootstrap 3.3.6 -- no change in IE11.  Should I create an issue for the update anyway?  It only requires changes to two file: deploy and the post header include.

**Comment by ksnortum** [comment]
Three files: also the footer include

**Comment by ksnortum** [comment]
Four and counting.  I better take a harder look at this

**Comment by glenl** [comment]
The editing  would be reduced if we simply called the folder "bootstrap" and identify it with a README file in that folder. Still, create an issue for this so the pull can reference that with a "close issue#".

**Comment by ksnortum** [comment]
Pull request #44
