### ISSUE TITLE
Search results page: FTP Area link not working in Windows

### ISSUE THREAD

**Issue by ksnortum** [MutopiaProject/MutopiaWeb#35]
This may be a Windows-only problem, but when I click on the FTP Area link in a search page, I get an error (the URL is pointing to somewhere that doesn't exist).

**Comment by glenl** [comment]
The fix for this was merged not so long ago in [MutopiaProject issue 662](https://github.com/MutopiaProject/MutopiaProject/issues/662). We should apply the same fix to stay consistent.

**Comment by ksnortum** [comment]
Pull request #38
