### ISSUE TITLE
Working prototype #2

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaWeb#40]
Since there have been several revisions to the code base and a new version of bootstrap, the task is to create a new iteration of the prototype. This also gives us the opportunity to incorporate some of the design work and discussion in issue #32 and, specifically, Paul's [prototype 18](http://clairnote.org/html5mutopia/index18.html).

**Comment by ksnortum** [comment]
@glenl So should I change *.html-in files to match Paul's prototype?  Just want to double check.

@PaulMorris Did you just modify the index.html by hand or did you use the *.html-in files and Perl scripts?  If you did it by hand the trick will be pulling those changes into the *.html-in.  If not, then can you post the *.html-in files here?

**Comment by PaulMorris** [comment]
> @PaulMorris https://github.com/PaulMorris Did you just modify the index.html by hand or did you use the *.html-in files and Perl scripts? If you did it by hand the trick will be pulling those changes into the *.html-in. If not, then can you post the *.html-in files here?

I just modified the html by hand, so it will need to be converted to the Perl script setup.  I should really clean it up some first.  I’d also like to try the in-place expanding/un-hiding functionality of bootstrap for those browse lists.  It doesn’t look difficult.  I’ll see if I can get to these things soon.

**Comment by PaulMorris** [comment]
I cleaned up index18 a bit.  There are still inline styles, etc, but that's just the stage we're in.  Feel free to work on converting it over to the Perl scripts for prototype 2.

**Comment by glenl** [comment]
@ksnortum, yes, modify the .html-in file directly for this. For prototypes I don't mind in-line styles but the end product will have all styles in the mutopia.css file.

**Comment by ksnortum** [comment]
Pull request #42
