### ISSUE TITLE
Download server throws 403 error

### ISSUE THREAD

**Issue by jonsger** [MutopiaProject/MutopiaWeb#97]
Hi,

when I try to get music sheets from mutopiaproject.org, I get always 403 (Forbidden) errors. E.g. [this link](http://www.mutopiaproject.org/ftp/BeethovenLv/O2/LVB_Sonate_02no1_1/LVB_Sonate_02no1_1-a4.pdf).

Jonathan

**Comment by glenl** [comment]
Confirmed. @chrissawer ?

**Comment by jonsger** [comment]
any update?

**Comment by dominicus** [comment]
Pages from the ftp folder seem to be serving now.

**Comment by jonsger** [comment]
Works again.
